### ISSUE TITLE
Module not found bug on running test 

### ISSUE THREAD

**Issue by hareshpatel1990** [markstory/cakephp-typescript-react#2]
### What I have Done
1. Clone git repo. by using command 
    `git clone https://github.com/markstory/cakephp-typescript-react.git cake-type`
2. Run following commands for install cakephp and typescript dependencies
    ```
    $cd cake-type
    $composer install
    $yarn  install
    ```
3. Run Test Commands
    `$yarn test`

### Bug
After step 3 i.e. run test command, I am getting error 
```
Test suite failed to run
Cannot find module 'cake-type/components/greet' from 'tests/js/spec/components/greet.test.tsx'
       2 | import {render} from '@testing-library/react';
       3 | 
     > 4 | import Greet from 'cake-type/components/greet';
         | ^
       5 | 
       6 | test('renders', function() {
       7 |   const {getByText} = render(<Greet />);

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (tests/js/spec/components/greet.test.tsx:4:1)
```

**Comment by markstory** [comment]
Why is the module `cake-type`? You would need to update the aliases for babel/jest to have that work.

**Comment by ishanvyas22** [comment]
@hareshpatel1990 there is no additional things you have to set or configure. I tried same steps you've mentioned but unable to replicate this issue, my tests are passing without any errors.

Can you please confirm if you've changed anything in any of the config files?
